# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f54bbc26a629b7ffd46ee67023a18befd2ebe47b2b5c5c319d66de5d65a98eecb066ebd96a423993a1a5acb2379bc7913bebc9f10e5eb365bc787d4c67979b6

test:
  secret_key_base: afdb40dc66834233e21de0f19089b2c00285deddd8943a4230df51c6263271fd21e4267384e971b89e79c17a642110b73425795ddc378645f9373ea9b7c38402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
